apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: genacr222.azurecr.io/chat:latest
          ports:
            - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 5555
      targetPort: 5555
  selector:
    app: chat-app
