# docker build -t chat . ; docker run -it chat /bin/bash
# docker build -t chat . ; docker run -p 5555:5555 chat


FROM python:3.9-slim

WORKDIR /app/

COPY ./server.py . 

EXPOSE 5555

CMD [ "python", "./server.py" ]

