# docker build -t chat . ; docker run -it chat /bin/bash
# docker build -t chat . ; docker run -p 5555:5555 chat


FROM python:3.9-slim

WORKDIR /app/

RUN apt-get update && apt-get install -y curl telnet

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./server.py . 

EXPOSE 5000

CMD [ "python","-u" ,"./server.py" ]

